### ISSUE TITLE
Broken date selector (availability)

### ISSUE THREAD

**Issue by FatzkeFTW** [esamarathon/user-management#20] opened 2019-03-28 19:18 UTC
This is what it looked like for zoton:
![](https://cdn.discordapp.com/attachments/449540590250622998/560902045146677258/unknown.png)

New users seem to unable to pick a date after the current one (today).

**Comment by CBenni** [comment] 2019-03-28 20:15
Can you provide more information? While the until-date is obviously wrong, in what manner does it break? Is there console errors?

**Comment by CBenni** [comment] 2019-03-28 20:16
Duplicate of https://github.com/esamarathon/user-management/issues/21, we will continue tracking this there

**Closed by CBenni** 2019-03-28 20:16 UTC
