### ISSUE TITLE
Can duplicate run submissions and edit them as a new submission

### ISSUE THREAD

**Issue by pandathesenpai** [esamarathon/user-management#30] opened 2019-03-28 20:08 UTC
https://i.imgur.com/eZqZJMP.png

You can keep on duplicating them and even edit them entirely

**Comment by CBenni** [comment] 2019-03-28 20:22
Duplicate of https://github.com/esamarathon/user-management/issues/25

**Closed by CBenni** 2019-03-28 20:22 UTC
